name: bittorrent-tracker-editor
adopt-info: mainprogram
icon: metainfo/io.github.gerryferdinandus.bittorrent-tracker-editor.png

base: core22
grade: stable
confinement: strict

architectures:
  - build-on: amd64
  - build-on: arm64

apps:
  bittorrent-tracker-editor:
    extensions:
      - kde-neon
    command: trackereditor
    environment:
      # Fallback to XWayland if running in a Wayland session.
      DISABLE_WAYLAND: 1
    plugs:
      - home
      - network
      - removable-media

parts:
  build_lazarus:
    source: .
    plugin: nil
    build-packages:
      - curl
      - build-essential
      - fpc
      - libqt5x11extras5-dev
    build-environment:
      - LAZARUS_URL_TAR_GZ: "https://sourceforge.net/projects/lazarus/files/Lazarus%20Zip%20_%20GZip/Lazarus%203.4/lazarus-3.4-0.tar.gz"
      - LAZARUS_QT_VERSION: "5"
      - LIB_DIR: "/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR"
      - LAZARUS_DIR: "$PWD/lazarus"
    override-build: |
      # Remove the older libQTpas.so
      rm -f $LIB_DIR/libQt${LAZARUS_QT_VERSION}Pas.*

      #Download lazarus source code. Directory 'lazarus' will be created in the root.
      curl -L -O $LAZARUS_URL_TAR_GZ
      tar -xzf *.tar.gz

      # Create libQTpas.so and put it in snap $CRAFT_PART_INSTALL
      cd "$LAZARUS_DIR/lcl/interfaces/qt${LAZARUS_QT_VERSION}/cbindings/"
      qmake
      make -j$(nproc)
      make install
      cp -av --parents $LIB_DIR/libQt${LAZARUS_QT_VERSION}Pas.* $CRAFT_PART_INSTALL

      # make lazbuild and put the link with extra parameter in /usr/bin/
      cd "$LAZARUS_DIR"
      make lazbuild
      echo "$LAZARUS_DIR/lazbuild --primary-config-path=$LAZARUS_DIR --lazarusdir=$LAZARUS_DIR \$*" > /usr/bin/lazbuild
      chmod 777 /usr/bin/lazbuild

  mainprogram: # Build and add to snap the main program: trackereditor
      after: [build_lazarus]
      source: .
      plugin: nil
      parse-info: [metainfo/io.github.gerryferdinandus.bittorrent-tracker-editor.metainfo.xml]
      override-build: |
        lazbuild --build-mode=Release --widgetset=qt5 source/project/tracker_editor/trackereditor.lpi
        install enduser/trackereditor $CRAFT_PART_INSTALL/

# --------------------------------------------------------------
# Only 2 files are explicitly added in this snap
# - main program: enduser/trackereditor
# - Lazarus QT suport library: libQt5Pas.so
#
# Create snap. Run from the project root folder:
# snapcraft --verbosity verbose
#
# he snapTo look what is inside t file. Directory 'squashfs-root' will be created in the root folder:
# unsquashfs *.snap
#
# Install the snap:
# sudo snap install --devmode ./*.snap 
#
# Run the snap
# snap run bittorrent-tracker-editor
# --------------------------------------------------------------
# Todo: building for QT6 is still not working with snap
# https://askubuntu.com/questions/1460242/ubuntu-22-04-with-qt6-qmake-could-not-find-a-qt-installation-of
# qtchooser -install qt{LAZARUS_QT_VERSION} $(which qmake6)
# export QT_SELECT=qt{LAZARUS_QT_VERSION}
# --------------------------------------------------------------
